apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment
  template:
    metadata:
      labels:
        app: consignment
    spec:
        containers:
        - name: consignment-service
          image: eu.gcr.io/my-project-tattoor/consignment-service:latest
          imagePullPolicy: Always
          command: [
            "./consignment-service",
            "--selector=static",
            "--registry=kubernetes",
            "--server_address=:8080"
          ]
          env:
          - name: DB_HOST
            value: "mongo:27017"
          - name: MICRO_BROKER
            value: "nats"
          - name: MICRO_BROKER_ADDRESS
            value: "nats:4222"
          - name: UPDATED_AT
            value: "Пн фев 11 17:18:00 MSK 2019"
          ports:
          - containerPort: 8080
            name: cons-port